# Example ruff configuration for Playwright Python projects
# File: pyproject.toml (add to your existing file)

[tool.ruff]
# Enable Playwright-relevant rules
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings  
    "F",   # Pyflakes
    "B",   # flake8-bugbear (catches common mistakes)
    "SIM", # flake8-simplify
    "RUF", # Ruff-specific rules
]

# Playwright-specific custom rules
[tool.ruff.lint]
ignore = [
    "E501",  # Line too long (Playwright selectors can be long)
]

# Custom rules for Playwright patterns
extend-select = ["B"]  # Catch sleep() usage, etc.

[tool.ruff.per-file-ignores]
"tests/**" = [
    "S101",  # Allow assert statements in tests
]